#!/usr/bin/bash

echo "Please enter a filename: "
read filename

if [[ -f $filename ]]; then
	#part 1
	echo "File does exist"
	sort $filename | uniq > clean1.txt
	echo "contents have been sorted and removed duplicate entries"

	#part 2
        grep -E '^[A-Za-z0-9]' clean1.txt > clean2.txt
        echo "Entries are matched (letters and digits)"

	#part 3
        grep -Pv '[\W_]{2,}' clean2.txt > clean3.txt
        echo "Content matched that does not contain consecutive non-alphanumeric characters"

	#part 4
	grep -E '@[A-Za-z0-9]+\.(com|org|net)$' clean3.txt > clean4.txt
	echo "Content matched valid domain name"
else
	echo "File does not exist"
	exit 1
fi

