#!/bin/bash

#minNumRoll=1
#maxNumRoll=20

#randomNumRoll=$((RANDOM % (maxNumRoll - minNumRoll + 1) + minNumRoll))

#echo "Here is a random number between 1 and 20: $randomNumRoll"

#echo "Enter a random number: "

#read userNum

#if [ userNum -lt 1 ]; then
#	echo "Error: input must be greater than 1."
#else
#	randomNumber=$((RANDOM % userNum + 1))
#	echo "Your number between 1 and $userNum is: $randomNumber"

#fi

#	randomNum=$((RANDOM % $1 + 1))
#	echo "Your number between 1 and $1 is: $randomNum"

#if [ -z "$1" ]; then
#	correctNum=0
#	while [ $correctNum -eq 0 ]; do
#		echo "Error: you must pass an argument."
#		read randomNum
#		if [ randomNum -gt 1 ]; then
#			correctNum=1
#		else
#			echo "Enter a number that is greater than 1."
#		fi

#	done
while true; do
echo "Enter the number of die you are rolling:"
read dieNum
echo "Enter the number of sides of the die you are rolling:"
read dieSides

if [ $dieNum -gt 0 ] && [ $dieSides -gt 0 ]; then
echo "Die number: $dieNum Die Sides: $dieSides"

else
echo "Error: Values must be numbers"
fi

for ((i=1; i<=dieNum; i++)) do
dieRoll=$((RANDOM % dieSides + 1))
echo "Die $i rolled a $dieRoll"
done
done
